### ISSUE TITLE
Black screen when used with xautolocker option in NixOS

### ISSUE THREAD

**Issue by sondr3** [Ma27/i3lock-pixeled#1]
I've just enabled the xautolocker script with your script for i3-lock and for some reason the screen just goes black instead of setting a screenshot. I'm not sure if there's something wrong on my end but I was wondering how you'd configure yours. Mine is:

```nix
      xautolock = {
        enable = true;
        locker = "${pkgs.i3lock-pixeled}/bin/i3lock-pixeled";
        time = 10;
      };
```

**Comment by Ma27** [comment]
could you please show me the logs of the `xautolock` service (can be retrieved with `journalctl --user -u xautolock.service`)

And does the script actually work for you when using it manually?
I'm quite confused that this caused a problem, I also use the `xautolock` module and until now it works fine (the only difference is that I have the notifier enabled, but I don't think that this should make a difference)

**Comment by sondr3** [comment]
For some reason `journalctl --user -u xautolock.service` only shows previously when it actually failed and not the last three hours or so instead when I started using your package. So it's probably not very useful. However, `systemctl --user status xautolock.service` shows this:

```sh
sondre@jupiter ~> systemctl --user status xautolock
● xautolock.service - xautolock service
   Loaded: loaded (/nix/store/r5vmzwp6hlgssggbpf9ilvxlffbh7hl8-unit-xautolock.service/xautolock.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-04-11 20:30:12 CEST; 3min 17s ago
 Main PID: 1264 (xautolock)
   CGroup: /user.slice/user-1001.slice/user@1001.service/xautolock.service
           └─1264 /nix/store/zwxhamy690xw4szn9dhnv83zlmh3q5as-xautolock-2.2/bin/xautolock -noclose -time 10 -locker /nix/store/50q9pzya85k8qrj2ccv3mqdiccc8wjfm-i3lock-pixeled-1.1.0/bin/i3lock-pixeled

Apr 11 20:30:12 jupiter systemd[1182]: Started xautolock service.
```

And yes, running it manually works just fine. I can try and let the computer lock itself sometime later tonight. You don't happen to have your configuration for xautolock available so I can look at it? I couldn't get the notification thing to work either.

**Comment by Ma27** [comment]
as I'm partially "responsible" for the `xautolock` module I have some config as well:

``` nix
{
    xautolock = {
      enable = true;
      enableNotifier = true;
      notifier = "${pkgs.libnotify}/bin/notify-send \"Locking in 10 seconds!\"";

      locker = with pkgs; "${i3lock-pixeled}/bin/i3lock-pixeled";
    };
}
```

However have you confirmed that the `/nix/store/...-unit-xautolock.service/...` actually invokes `i3lock-pixeled`? NixOS uses internally a Perl script named `switch-to-configuration.pl` to activate configurations and restart services. As it doesn't support user services (and xautolock is implemented as such) it won't refresh the service, my current workaround for this is to simply restart my `i3`.

**Comment by sondr3** [comment]
Just tried again with

```nix
      xautolock = {
        enable = true;
        enableNotifier = true;
        notifier = "${pkgs.libnotify}/bin/notify-send \"Locking in 10 seconds\"";
        locker = "${pkgs.i3lock-pixeled}/bin/i3lock-pixeled";
        time = 10;
      };
```

`journalctl --user -u xautolock.service`:

```sh
-- Reboot --
Apr 11 21:22:23 jupiter systemd[1174]: Started xautolock service.
Apr 11 21:35:30 jupiter i3lock[1926]: pam_unix(i3lock:auth): authentication failure; logname= uid=1001 euid=1001 tty=:0 ruser= rhost=  user=sondre
```

The error is from me hitting enter because the screen was black and I wanted to test if the screen was only blank or if the locker turns on. It turns on and notifies me and everything but the screenshot is black for some reason.

**Comment by Ma27** [comment]
according to the the `-- Reboot --` I can assume that you restarted your machine and the service actually uses my script, right?

I'm sorry, but I'm currently not sure, what *exactly* is causing your issue. Could you create a minimal NixOS configuration where you were able to reproduce the issue? Otherwise I'll have a deeper look at it tomorrow in order to check if I'm currently missing something :)

**Comment by sondr3** [comment]
Yeah, sorry, should've specified. I updated my script and rebooted my computer, I still haven't figured out how to log out from bspwm yet (but to be fair I've been too lazy to care about it). I'll try to see if I can figure something out.

**Comment by Ma27** [comment]
ok, go on and ping me if you need something :)

I just tried to reproduce it with the following config for a NixOS VM:

``` nix
{
  bspwm_i3lock = { pkgs, ... }: {
    users.extraUsers.vm = {
      password = "vm";
      extraGroups = [ "wheel" ];
      isNormalUser = true;
    };

    services.xserver = {
      enable = true;
      windowManager.default = "bspwm";
      windowManager.bspwm.enable = true;
      windowManager.bspwm.sxhkd.configFile = "${pkgs.bspwm}/share/doc/bspwm/examples/sxhkdrc";

      xautolock = {
        enable = true;
        enableNotifier = true;
        notifier = "${pkgs.libnotify}/bin/notify-send \"Locking in 10 seconds\"";
        locker = "${pkgs.i3lock-pixeled}/bin/i3lock-pixeled";
        time = 1;
      };
    };

    environment.systemPackages = [ pkgs.i3lock-pixeled pkgs.rxvt_unicode ];
  };
}
```

Invoking `i3lock-pixeled` from `urxvt` and the autolock (both with pixellated background) work absolutely fine for me...

**Comment by sondr3** [comment]
I haven't gotten any further but I attempted to use some of the other i3lock variants and they all have the same problem so I'm going to assume that this is an issue with my machine morso than it is with your script. Fairly certain it has to do with Nvidia, which sucks ass on Linux. I'll attempt to use the integrated card instead for a test some time during the weekend.

**Comment by Ma27** [comment]
awesome (and thanks for the investigation!) Just ping me if you need further support! :)

**Comment by sondr3** [comment]
It is somehow my Nvidia card, I've disabled it and switched to the integrated one and that works fine. Not really sure why but hey, it's something at least. Thanks for the help! :smile:

**Comment by Ma27** [comment]
great! :)
